### ISSUE TITLE
Consolidate css style

### ISSUE THREAD

**Issue by camerican** [camerican/NYCDA_SCC16_Diane#4]
For the 3-column layout there are three classes: 
- textbox
- textbox2
- textbox3

which all apply the same style:

``` css
.textbox{
    width:190px;
    height:600px;
    font-family: times;
    font-size: 14px;
    text-align: left;
    padding:10px;
    float:left;
}
.textbox2{
    width:190px;
    height:600px;
    font-family: times;
    font-size: 14px;
    text-align: left;
    padding:10px;
    float:left;
}
.textbox3{
    width:190px;
    height:600px;
    font-family: times;
    font-size: 14px;
    text-align: left;
    padding:10px;
    float:left;
}
```

It would be better to only define **.textbox** class and then have all columns use that styling.
